name: newtmgr
version: 0.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  cbor:       ^3.2.0  #  CBOR Encoder and Decoder. From https://pub.dev/packages/cbor
  typed_data: ^1.1.6  #  Helpers for Byte Buffers. From https://pub.dev/packages/typed_data
